### ISSUE TITLE
vCloud AMQP Exchange type

### ISSUE THREAD

**Issue by EvgBoor** [vmware/container-service-extension#187]
We use our own system of automation which use routing on RabbitMQ Exchange level. But if we try install cse, we have error about type of RabbitMQ Exchange - pika.exceptions.ChannelClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'type' for exchange 'vcdExchange' in vhost '/': received 'direct' but current is 'topic'").  We use topic type of Exchange for routing.
If we try use alternate-exchange on RabbitMQ Exchange we also get an error - pika.exceptions.ChannelClosed: (406, "PRECONDITION_FAILED - inequivalent arg 'alternate-exchange' for exchange 'vcdExchange' in vhost '/': received none but current is the value 'vcdExchangeAlternative' of type 'longstr'")

In this case, we cannot organize message routing for vCloud Events for example.

**Comment by EvgBoor** [comment]
Any idea ?

**Comment by rocknes** [comment]
Hi @EvgBoor 

Which version of CSE and vCD are you using?
Can you please upload the cse logs and the config file that's being used in this case? Please feel free to redact server fqdn, ip, username, password or other sensitive information from the files.

Regards
Aritra Sen

**Comment by rocknes** [comment]
We had an internal discuss and we realized that if CSE is installed with the config file that has the same amqp section as the default config file (generated by cse sample command), the observed issue will manifest. 

'vcdext' is the global extension exchange of vCD, directing CSE to use it, involves reconfiguring it and overwriting it's configuration. The default value for exchange name provide by CSE in the config is faulty and we plan to fix it  in an upcoming release. In the meantime as a workaround, you can update the amqp section of the config file to specify a new exchange.

amqp:
  exchange: <*cse-exclusive-exchange*>
  host: 'fqdn of amqp server'
  password: <super secret>
  port: 5672
  prefix: vcd
  routing_key: cse
  ssl: false
  ssl_accept_all: false
  username: <username>
  vhost: /

And re run the command cse install,  this should create the new exchange. and if CSE prompts to update AMQP exchange info in vCD, please decline.

**Comment by EvgBoor** [comment]
Do not you tell me the approximate release date?

**Comment by andrew-ni** [comment]
We had an implementation mistake on our end, as described by @rocknes. 

PR #206 will fix this.

**Comment by andrew-ni** [comment]
More info for CSE users experiencing this bug

The issue boils down to the fact that the ‘exchange’ specified in CSE config file ‘amqp’ section should be unique to CSE, and not be an exchange that already exists for any other purpose. This is because CSE requires a specific exchange type (direct), and to avoid any side effects to processes using any pre-existing exchange(s).

If you’re facing this issue, you can just specify a different exchange name in the CSE config file ‘amqp:exchange’ section, and running `cse install ...` will go ahead and create this new exchange. Then when CSE server is started (`cse run ...`) using this same config file, this new exchange will be used.
