### ISSUE TITLE
vcd cse cluster config <non-existing-cluster> fails with wrong error message 

### ISSUE THREAD

**Issue by sakthisunda** [vmware/container-service-extension#380]
- When executing vcd cse cluster config <non-existing-cluster> the following error message is displayed.

    vcd cse cluster config unknown-cluster
 
    Usage: vcd cse cluster config [OPTIONS] NAME

    Try "vcd cse cluster config -h" for help. 

    Error: Unknown error. Please contact your system administrato
 
- Previous CSE versions displayed the following error message :

  vcd cse cluster info unknown-cluster

  Usage: vcd cse cluster info [OPTIONS] NAME

   Try "vcd cse cluster info -h" for help.

   Error: Cluster unknown-cluster not found either in vCD or PKS

**Comment by rocknes** [comment]
The config command is a special one because it's the only one that makes a request to the CSE server with Accept header set to 'x-yaml'.

In this case the cluster is not found on CSE server and a 404 is sent back, however the server is sending back json while ignoring the Accept header sent by client. As a result of this miss match the client is unable to parse the error response back properly and raising the default-catch-all error message.

**Comment by andrew-ni** [comment]
Fixed in #419
