### ISSUE TITLE
vcd cse ovdc as a System logged in user error

### ISSUE THREAD

**Issue by flamby** [vmware/container-service-extension#430]
Hi,

Tested on CSE 2.0.0 and VCD 9.1.0.3.

When logged in as a VCD System user, one could expect to be able to list registered org vdc (native or PKS).

```vcd cse ovdc list```
The following error is raised
```
Usage: vcd cse ovdc list [OPTIONS]
Try "vcd cse ovdc list -h" for help.

Error: Expecting value: line 1 column 1 (char 0)
```

From a CSP perspective, with K8S managed services in mind, it would be more than useful to be able to deploy clusters in multiple organizations using a VCD System account, instead of having to create a local org admin user for every organizations. Automation of several org's clusters creation would be much simpler then.

Thanks

**Comment by flamby** [comment]
@andrew-ni @rocknes @harshneelmore @sakthisunda

**Comment by sakthisunda** [comment]
Hi,
We guess this could be due to server side processing taking more than default timeout. Can you please increase the server time out value? This should be done on vCloud Director. The instructions for increasing the server time out are under:https://vmware.github.io/container-service-extension/CSE_ADMIN.html

For your convenience, I pasted them below. Here I set it to 40 seconds for example. 

If you still see the same error, please attach the log files for further debugging with this issue: cse-server-debug.log, vcd.log ( preferably all log files you see )/

thanks.

--------------------------------------------------------------------------------------------
Setting the API Extension Timeout
The API extension timeout is the number of seconds that vCD waits for a response from the CSE server extension. The default value is 10 seconds, which may be too short for some environments. To alter the time follow the steps shown below.

Configure the API extension timeout (seconds) on the vCloud Director cell:

cd /opt/vmware/vcloud-director/bin
./cell-management-tool manage-config -n extensibility.timeout -l
./cell-management-tool manage-config -n extensibility.timeout -v 40
--------------------------------------------------------------------------------------------

**Comment by flamby** [comment]
Hi @sakthisunda 

This setting was already at 20 instead of 10, since I followed the documentation.

Increasing it to 40 does not solve the issue.

In case it had worked, retrieving all vDCs in a such amount of time would mean a design problem.
Listing all org vdc is a matter of 1 or 2 REST API calls (depending on the pagination you use and the number of org vdc exceeding 128 or not) using the VCD query API (`query?type=adminOrgVdc`)

Does it work in your lab w/ a login like this?

```
vcd login fqdn_vcd_endpoint System administrator --password <password>
vcd cse ovdc list
```

I think it can be a problem of `vcd-cli` itself, since `vcd vdc list` return nothing (at least it does not raise an error).

Hopes it helps.

**Comment by sakthisunda** [comment]
I could not reproduce this issue with vCD 9.1.0, CSE 2.0.0 . I tried the command with three different personas: sys admin, org admin and regular tenant user. In all the cases, I get the correct results.

 If I see anything else caused this error, I will update this post again.

In the mean time, after running the command when it causes the error, please get the log files: vcd.log, cse-logs/cse-server-debug.log (preferably all the log files, you notice). thanks

Logged in as System administrator:
-----------------------------------

(vcd2) sakthis@sakthis-a01 vcd2.0.0 $ vcd cse version
CSE, Container Service Extension for VMware vCloud Director, version 2.0.0
(vcd2) sakthis@sakthis-a01 vcd2.0.0 $ vcd login 10.150.201.33 System administrator -iwp ca\$hc0w
administrator logged in, org: 'System', vdc: ''
(vcd2) sakthis@sakthis-a01 vcd2.0.0 $ vcd cse ovdc list
name         org      k8s_provider
-----------  -------  --------------
cse-org-vdc  cse-org  none
new-org-vdc  new-org  none

Logged in org administrator:
----------------------------
(vcd2) sakthis@sakthis-a01 vcd2.0.0 $ vcd login 10.150.201.33 cse-org org-administrator -iwp ca\$hc0w
org-administrator logged in, org: 'cse-org', vdc: 'cse-org-vdc'
(vcd2) sakthis@sakthis-a01 vcd2.0.0 $ vcd cse ovdc list
name         org      k8s_provider
-----------  -------  --------------
cse-org-vdc  cse-org  none

Logged in as tenant user ( Created 'new-user') as user in org 'new-org'
----------------------------------------------------------------------
(vcd2) sakthis@sakthis-a01 vcd2.0.0 $ !10032
vcd login 10.150.201.33 new-org new-user -iwp ca\$hc0w
new-user logged in, org: 'new-org', vdc: 'new-org-vdc'
(vcd2) sakthis@sakthis-a01 vcd2.0.0 $ vcd cse ovdc list
name         org      k8s_provider
-----------  -------  --------------
new-org-vdc  new-org  none

**Comment by sakthisunda** [comment]
I also thought on any other situation that cause the command to break not only for vcd cse ovdc list ; but for any vcd cse command.

If the AMQP server is down or intermittently fail, the following error exactly as you experienced was observer:

(vcd2) sakthis@sakthis-a01 vcd2.0.0 $ vcd cse ovdc list
Usage: vcd cse ovdc list [OPTIONS]
Try "vcd cse ovdc list -h" for help.

Error: Expecting value: line 1 column 1 (char 0)

**Comment by flamby** [comment]
Hi @sakthisunda

> I also thought on any other situation that cause the command to break not only for vcd cse ovdc list ; but for any vcd cse command.
> 
> If the AMQP server is down or intermittently fail, the following error exactly as you experienced was observer:

The AMQP connection is working (test ok), and since we have a third-party tool using it, we would have an alarm if it's not working as expected.

Can we increase somehow the log verbosity of the CLI?
Maybe by adding some `print()` output somewhere.

TIA

**Comment by sakthisunda** [comment]
Log files are quite informative to debug:
For example in my cse-logs/cse-server-debug.log, I have the following error recorded when I get the error on not able to connect to AMQP server.
    
```
callback(*args, **keywords)
  File "/Users/sakthis/.virtualenvs/vcd2/lib/python3.7/site-packages/pika/connection.py", line 1857, in _on_connection_error
    self.params.connection_attempts)
pika.exceptions.AMQPConnectionError: Connection to 10.150.201.111:5672 failed: timeout
```

 When the CSE server times out, we get the following error.

`container_service_extension.exceptions.VcdResponseError: External service 'cse' failed to respond in the specified timeout (10 SECONDS)`

As I suggested earlier, please get the log files: **vcd.log, vcd_cli_error.log, cse-logs/cse-server-debug.log (preferably all the log files, you notice getting created)**. That may help in knowing the cause of error at the time of failure.

**Comment by flamby** [comment]
Hi @sakthisunda 

Sorry for the late reply.

Since logs contain sensitive data sometimes, is it possible to open an SR and continue troubleshooting there?

TIA

**Comment by sakthisunda** [comment]
Thanks for the log files. After investigation of log file, I noticed the following entries in cse-server-debug.log as last recent timestamps (23rd and 30th)

`19-09-23 16:14:38 | callback:239 - process | ERROR :: Calling <bound method Connection._on_connection_error of <SelectConnection CLOSED socket=None params=<ConnectionParameters host=46.21.203.122 port=5672 virtual_host=/ ssl=False>>> for "0:_on_connection_error" failed
Traceback (most recent call last):
  File "/usr/local/lib/python3.7/site-packages/pika/adapters/base_connection.py", line 432, in _handle_read
    data = self.socket.recv(self._buffer_size)
TimeoutError: [Errno 110] Connection timed out
pika.exceptions.AMQPConnectionError: (-1, "TimeoutError(110, 'Connection timed out')")
19-09-23 16:14:38 | consumer:214 - stop | INFO :: Stopping
`

After a week, with timestamp 19-09-30, log file recorded the list of ovdcs 
`19-09-30 22:34:46 | consumer:183 - on_message | DEBUG :: reply: "[{\"name\": \"VDC_Diem_PERDIDI_1017164\", \"org\": \"Diem_PERDIDI_1017164\", \"k8s_provider\": \"none\"}, {\"name\": \"VDC_SmartCaisse_1009639\",
......`

This exactly what I validated in the previous postings above in this thread. Connection to AMQP caused the error: `Expecting value: line 1 column 1 (char 0)`

Make sure that your AMQP server is reachable. In the log file you had AMQP connection on 19-09-30.  

I would conclude the root cause is AMQP server connection failure. Also, please restart CSE server if you bring up AMQP server and running.

If everything is up and running (AMQP, vCD), I don't see this error. It is not reproducible. Hope this helps. 

Please also upload your vcd_cli_error.log, vcd.log. You should see the error recorded as
`  raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)`

**Comment by flamby** [comment]
Hi @sakthisunda 

Thanks to your investigation, I think I figured out what's going on.

The AMQP server is working fine, we can telnet the AMQP port from the CSE server.
Also, a third-party tool (Zerto) uses it on a regular basis without issue.
But this third party tool requires a "topic" exchange, instead of a "direct" exchange, that CSE had hard-coded for its `pika` connections.

I forgot that I had to change in the first place the exchange's type temporarily by re-creating the exchange in order to install CSE.

So, this time, I looked in the python code to force the `pika` connection to be for a `topic` exchange in the hope that it won't be incompatible w/ CSE behaviour.

_/usr/local/lib/python3.7/site-packages/container_service_extension/utils.py_
```python
#EXCHANGE_TYPE = 'direct'
EXCHANGE_TYPE = 'topic'
```
For now, I created a cluster but the `vcd vdc list` or `vcd cse ovdc list` commands still fail.
Does it mean that most cluster operations do not require AMQP connection, but vdc listing for instance does?

Do you think the exchange type can be the root cause?
By looking at their codes, `vcd-cli` nor `pyvcloud` do not seem to have hard-coded `direct` exchange type as a pre requisite.

I see the `cse` routing key on the exchange from the rabbitmq UI, and see messages from time to time.

TIA

**Comment by sakthisunda** [comment]
In RabbitMQ binding gets set up between the queue and the exchange. In this case, we may have bindings to two different queues from the exchange for two exchange types for same routing key. It may be possible that consumer is listening to only of the queue.

By the way, only commands that start with `vcd cse` go thru AMQP (vcd cse ovdc list, vcd cse cluster create).  Regular `vcd` commands don't go thru AMQP (examples: vcd vdc list ).

Same routing key, same exchange name with different exchange type might cause vcd cse commands does not forward the command correctly to the right queue. 

Changing the exchange type and not doing a clean setup/configuration of AMQP would be a concern. For example, changing exchange type and just doing `cse run -c <config>` won't complain. But `cse install -c ` would complain that you have a channel already exist with different exchange type etc. So, a clean-up of the channels is required. Please check with rabittmq command reference. 

Please check with commands like `rabbitmqctl list_bindings
 rabbitmqctl list_consumers, rabbitmqctl list_exchanges` to get clear idea of what is going on when you have multiple exchanges, queues and routing keys. Tweaking rab

**Comment by flamby** [comment]
I did a clean re-install, by unregistering the cse extension, and do the `cse install -c`

Here are rabbitmqctl commands output.

**list_bindings**
```
Listing bindings ...
        exchange        VCD     queue   VCD     []
        exchange        ZertoVcdQueue-2feef8d0-d29c-4981-beff-7870339ec881
queue   ZertoVcdQueue-2feef8d0-d29c-4981-beff-7870339ec881      []
        exchange        cse     queue   cse     []
        exchange        vcd.ext.replyQueue.55c5c78a-5f50-47ae-8bc5-1c3c2e47c6e9
queue   vcd.ext.replyQueue.55c5c78a-5f50-47ae-8bc5-1c3c2e47c6e9 []
        exchange        vcd.ext.replyQueue.e4d6968f-5649-4695-a11b-27134ba79b52
queue   vcd.ext.replyQueue.e4d6968f-5649-4695-a11b-27134ba79b52 []
        exchange        vcd.infra.federation.queue      queue   vcd.infra.federa
tion.queue      []
        exchange        vcd.replyQueue.55c5c78a-5f50-47ae-8bc5-1c3c2e47c6e9
queue   vcd.replyQueue.55c5c78a-5f50-47ae-8bc5-1c3c2e47c6e9     []
VCD     exchange        ZertoVcdQueue-2feef8d0-d29c-4981-beff-7870339ec881
queue   #       []
VCD     exchange        cse     queue   cse     []
VCD     exchange        VCD     queue   true.*.*.*.com.vmware.vcloud.event.*.*
[]
vcd.replyExchange       exchange        vcd.replyQueue.55c5c78a-5f50-47ae-8bc5-1
c3c2e47c6e9     queue   vcd.replyQueue.55c5c78a-5f50-47ae-8bc5-1c3c2e47c6e9
[]
```
**list_consumers**
```
Listing consumers ...
[]      []      []      []      []      []
[]      []      []      []      []      []
[]      []      []      []      []      []
ZertoVcdQueue-2feef8d0-d29c-4981-beff-7870339ec881      <rabbit@ZVMCloud.3.852.0
>       Zerto   false   0       []
cse     <rabbit@ZVMCloud.3.24446.16>    ctag1.9764ecb8e5d847859e75cbb6871cfbbf
true    0       []
[]      []      []      []      []      []
vcd.ext.replyQueue.55c5c78a-5f50-47ae-8bc5-1c3c2e47c6e9 <rabbit@ZVMCloud.3.538.0
>       amq.ctag-RhnoWfh-MkCNY340Y5eo6Q true    1       []
```

**list_exchanges**
```
Listing exchanges ...
vcd.replyExchange       topic
amq.direct      direct
vcd.notifications20     topic
amq.fanout      fanout
amq.headers     headers
amq.match       headers
amq.rabbitmq.trace      topic
amq.topic       topic
amq.rabbitmq.log        topic
VCD     topic
        direct
```

Hopes it helps.

**Comment by sakthisunda** [comment]
For example, this is my amqp section in the configuration:
```
amqp:
  exchange: cse-ext
  host: bos1-vcd-sp-static-201-111.eng.vmware.com 
  password: guest
  port: 5672
  prefix: vcd
  routing_key: cse
  ssl: false
  ssl_accept_all: false
  username: guest
  vhost: /

```
Notice above that I have unique exchange name `cse-ext` ( **no reusing any existing exchange name from current vCD UI AMQP broker settings**)  and routing_key `cse` which is used exclusively for cse. 

With my configuration I executed the rabbitmqctl command below.  See that exchange name and queue name `cse-ext` and `cse`.  At this time, I also have cse up and running. (cse run)

```
[root@bos1-vcd-sp-static-201-111 ~]# rabbitmqctl list_exchanges
Listing exchanges for vhost / ...
name	type
cse-ext	direct
vCD_topic_exchange	topic

[root@bos1-vcd-sp-static-201-111 ~]# rabbitmqctl list_queues
Timeout: 60.0 seconds ...
Listing queues for vhost / ...
name	messages
cse	0

[root@bos1-vcd-sp-static-201-111 ~]# rabbitmqctl list_bindings
Listing bindings for vhost /...
source_name	source_kind	destination_name	destination_kind	routing_key	arguments
cse-ext	exchange	cse	queue	cse	[]

[root@bos1-vcd-sp-static-201-111 ~]# rabbitmqctl list_consumers
Listing consumers on vhost / ...
queue_name	channel_pid	consumer_tag	ack_required	prefetch_count	arguments

cse	<rabbit@bos1-vcd-sp-static-201-111.2.9111.0>	ctag1.f08e255049494704b8b084c0faddcb6a	true	0	[]
cse	<rabbit@bos1-vcd-sp-static-201-111.2.9102.0>	ctag1.0cca98ed86fe4a3e886c334db5df2ef2	true	0	[]
cse	<rabbit@bos1-vcd-sp-static-201-111.2.9088.0>	ctag1.365e49c0f7b74fe4905f8fba2e9dff62	true	0	[]
cse	<rabbit@bos1-vcd-sp-static-201-111.2.9075.0>	ctag1.4e0883a8df9c4b439d779441fdfabb7f	true	0	[]
cse	<rabbit@bos1-vcd-sp-static-201-111.2.9063.0>	ctag1.e42c2f4c34134e94b2f38cb572413b5e	true	0	[]

```


1. CSE recommends unique exchange and routing key used for CSE only.
2. Supporting different exchange type by tweaking source code is out of scope. We may do this experiment and enhancement in future. 
3. With the recommended setup and configuration, this bug is not reproducible unless AMQP server is down. Any time consuming vcd cse commands give timeout error.

From your rabbitmqctl commands output, I guess :

1. You are using VCD as exchange and exchange type topic (currently we support "direct" only)
```
VCD     topic
```

2. VCD appears with two different routing_keys in rabbitmqctl list_bindings
```
VCD     exchange        cse     queue   cse     []
VCD     exchange        VCD     queue   true.*.*.*.com.vmware.vcloud.event.*.*
[]

```
Thanks

**Comment by flamby** [comment]
Hi @sakthisunda 

If CSE requires an unique exchange, then the way to re-route an existing exchange (used by third-parties tools) under RabbitMQ should be documented, because most VCD platforms use one, whether it is for backup or DR/BC software.

I tried to follow RabbitMQ [exchange-to-exchange bindings documentation](https://www.rabbitmq.com/e2e.html) but failed to the dedicated CSE exchange receiving messages.

**Comment by andrew-ni** [comment]
Hi @flamby , are you still having issues with this?

Just for clarification on how CSE uses AMQP to talk to vCD:
The AMQP exchange must be a unique 'direct' exchange. Only CSE should be using this exchange. This is done by changing the `amqp: exchange:` value in CSE config file, and then running `cse install -c myconfig.yaml`, which will create this new amqp exchange. There's no need to go into RabbitMQ to make this change.

This issue seems very similar to the one discussed here: https://github.com/vmware/container-service-extension/issues/187#issuecomment-488367323

**Comment by flamby** [comment]
Hi @andrew-ni 

Are you saying that the dedicated CSE exchange does not have to be the one configured in VCD?
If so, then, it's easy for me to fix the issue.

Otherwise, as I have two third-parties tools which needs the VCD exchange to be of `topic` type, then I'm still in a dead-end, unable to configure RabbitMQ to do exchange-to-exchange binding in order to have a `direct` type exchange receiving the exact same messages than my current `topic` type exchange from VCD.

I hope I clarified the issue.

TIA

> Hi @flamby , are you still having issues with this?
> 
> Just for clarification on how CSE uses AMQP to talk to vCD:
> The AMQP exchange must be a unique 'direct' exchange. Only CSE should be using this exchange. This is done by changing the `amqp: exchange:` value in CSE config file, and then running `cse install -c myconfig.yaml`, which will create this new amqp exchange. There's no need to go into RabbitMQ to make this change.
> 
> This issue seems very similar to the one discussed here: [#187 (comment)](https://github.com/vmware/container-service-extension/issues/187#issuecomment-488367323)

**Comment by andrew-ni** [comment]
@flamby , the dedicated CSE exchange _**should not**_ be the one configured in vCD. If the dedicated CSE exchange and the vCD-configured exchange are the same, then this can lead to undefined behavior between vCD, CSE, and other extensions (we've seen this before with other users, and it's very difficult to debug)

You do not need to do anything in vCD extensibility UI or RabbitMQ to get this CSE exchange set up.

CSE requires a 'direct' exchange type, and `cse install ...` will create this exchange if the config file `amqp: exchange: ` name is unique.

example config file amqp section:
```
amqp:
  exchange: my-cse-exchange # cse exclusive exchange used by amqp server
  host: xxxxxxx
  password: guest
  port: 5672
  prefix: vcd
  routing_key: cse
  ssl: false
  ssl_accept_all: false
  username: guest
  vhost: /
```

**Comment by flamby** [comment]
Hi @andrew-ni 

Thanks for the clarification. I think the documentation should specify it more explicitly, as it's often necessary for third-parties tools to leverage the VCD exchange.

I'll reinstall CSE and keep you updated.

Thanks,

BR

> @flamby , the dedicated CSE exchange _**should not**_ be the one configured in vCD. If the dedicated CSE exchange and the vCD-configured exchange are the same, then this can lead to undefined behavior between vCD, CSE, and other extensions (we've seen this before with other users, and it's very difficult to debug)
> 
> You do not need to do anything in vCD extensibility UI or RabbitMQ to get this CSE exchange set up.
> 
> CSE requires a 'direct' exchange type, and `cse install ...` will create this exchange if the config file `amqp: exchange: ` name is unique.
> 
> example config file amqp section:
> 
> ```
> amqp:
>   exchange: my-cse-exchange # cse exclusive exchange used by amqp server
>   host: xxxxxxx
>   password: guest
>   port: 5672
>   prefix: vcd
>   routing_key: cse
>   ssl: false
>   ssl_accept_all: false
>   username: guest
>   vhost: /
> ```

**Comment by andrew-ni** [comment]
@flamby , those logs seem to describe a user error. Can you verify these things:

- Make sure only 1 CSE server is running for that vCD (none running in background or other terminals)

**Comment by flamby** [comment]
@andrew-ni 

I restarted everything, just to be sure, but still get an error regarding the `vcd cse ovdc list` command :

```
vcd cse ovdc list
Usage: vcd cse ovdc list [OPTIONS]
Try "vcd cse ovdc list -h" for help.

Error: Unknown error. Please contact your System Administrator
```

```
vcd cse system info
property              value
--------------------  ------------------------------------------------------
all_threads           6
config_file           config.yaml
consumer_threads      5
description           Container Service Extension for VMware vCloud Director
product               CSE
python                3.7.4
requests_in_progress  0
status                Running
version               2.5.0
```

Attempt to create a cluster (which worked BTW with CSE 2.0) leads to this error (same error with other templates from `vcd cse template list`
```
vcd cse cluster create myK8S -v ACME-01 -o ACME -n ROUTED --ssh-key ~/.ssh/authorized_keys -t ubuntu-16.04_k8-1.15_weave-2.5.2 -r 1
Usage: vcd cse cluster create [OPTIONS] NAME
Try "vcd cse cluster create -h" for help.

Error: '<' not supported between instances of 'NoneType' and 'int'
```

I've uploaded the new logs on the SR.

**Comment by andrew-ni** [comment]
Hi @flamby , this specific error: `Error: '<' not supported between instances of 'NoneType' and 'int'` during cluster creation is actually a known issue that will be fixed by #459 . As a workaround, provide the `-N` option (number of worker nodes). Please try running that cluster create command again. Also try other `vcd cse...` commands to see if they work. (something like cluster list)

Also, we're not seeing the logs on the SR

**Comment by flamby** [comment]
Hi @andrew-ni 

> Hi @flamby , this specific error: `Error: '<' not supported between instances of 'NoneType' and 'int'` during cluster creation is actually a known issue that will be fixed by #459 . As a workaround, provide the `-N` option (number of worker nodes). Please try running that cluster create command again.
 
The command works indeed if `-N` is provided. Thanks.

> For the ovdc list error, how many ovdcs do you have in your vCD? We're thinking that CSE may be timing out while going through a large amount of ovdcs, especially if other commands are working fine. 

We have 258 org vdc. 

`vcd cse ovdc list` should rely only on the query API `/query?type=adminOrgVdc&pageSize=128` so in my case, a matter of 3 REST calls because of 3 pages of 128 records needed to handle my 258 org vdc).

It should not do 258 REST calls to the detail view (so to speak) of all vdc. 
Or it may need caching on your side if you must do it to retrieve some attributes that aren't available in the Query API records specific to org vdc. My 2 cents. 

>You could test if this is the case by creating an org with a single ovdc and a single org admin user. 

It works like this of course. The purpose of this issue was to support CSP needs, i.e. ability from a system account to create _en masse_ many K8S clusters in different organizations.

>Login (vcd-cli) as that org admin, and try running this ovdc list command again. If this works, then >you're having a timeout issue. The workaround for now would be extending vCD's response time >using **cell-management-tool**. We would have to make a code change if this is actually the issue.

I already increased the timeout of the cell to 40 seconds.

I'm afraid that if my assumption is correct (i.e. CSE does 258 REST calls in my case), even a timeout of 600 seconds won't be enough. You must change the logic of retrieving information in order to support real VCD production platforms with hundreds of org vdc for this SP use-case.

> 
> We're also not seeing the logs on the SR.

They are on ftpsite.vmware.com SR directory (19069482210 ) like previously.
I uploaded new logs  : `cse-2.5_20191018.tgz`

**Comment by andrew-ni** [comment]
@flamby Thanks for the update. CSE will require design/implementation changes to be able to handle operations of this scale. CSE makes an API call per org vdc in order to access CSE-relevant org vdc metadata. I believe the only workaround for now would be to extend the cell timeout to be able to wait for that many requests. This is documented in #465 

As for the topic of this issue, it seems like the AMQP confusions have been solved, and we'll update the documentation to clarify that amqp exchange confusion (#465).

Do you have any further concerns? I think this issue can be closed if there's no further concerns

**Comment by flamby** [comment]
Hi @andrew-ni 

Understood. Please keep in mind that CSE is really interesting for CSP, so I think this design change makes sense.

**Comment by goelaashima** [comment]
Hi flamby

I am curious about CSE's use-case in CSP. Could you elaborate more? Also, which VMware Cloud Partner do you represent, it would be interesting for us to know.

Best.
Aashima
