### ISSUE TITLE
access to nodes after resize

### ISSUE THREAD

**Issue by kozy** [vmware/container-service-extension#536]
Hi guys, using the ```vce cse resize``` command, I cannot access the newly created nodes. It seems the ssh public key is not provided to them. What would be the recommended way to access the new nodes? Thanks!

**Comment by rocknes** [comment]
Hi Kozy,

We are aware of the deficiency in the `vcd cse cluster resize` interface and we will fix this in a future release. In the meantime, if you had provided a ssh key during template creation, that ssh key can be used to log into the newly added vm. Otherwise you can open up a webconsole to the vm from vcenter and add the ssh key manually.

Regards
Aritra Sen

**Comment by rocknes** [comment]
fyi : https://github.com/vmware/container-service-extension/pull/548 :)

**Comment by kozy** [comment]
I see, thanks, yes I found out that is an option. Sadly our situation currently is that the host provides those templates. However thanks for normalizing those options among commands! Does make sense I think : )
