### ISSUE TITLE
Ubuntu 16.04 template preparation fails

### ISSUE THREAD

**Issue by jondwaite** [vmware/container-service-extension#67]
Encountering 2 errors when using cse-install with the Ubuntu 16.04 template - both apparently being caused in /scripts/cust-ubuntu-16.04.sh:

1) The growpart /dev/sda 1 followed by resize2fs /dev/sda1 gives an error (unable to grow), since /dev/sda1 is already occupying the full (10GB) disk space in the ubuntu-temp VM. Not sure if this is due to a previous disk resize failing in my environment or not. Due to the error the script exits and no further customisation is performed.

2) Ubuntu has a strange habbit of attempting to connect to archive.ubuntu.com and security.ubuntu.com on IPv6 (even when the primary NIC doesn't have IPv6 configuration enabled). This results in the 'apt-get' lines getting stalled waiting for an IPv6 response on networks which don't have this configured.

Adding the following near the top of cust-ubuntu-16.04.sh disables this behaviour and allows updates to be retrieved/processed correctly:
echo 'net.ipv6.conf.all.disable_ipv6 = 1' >> /etc/sysctl.conf
echo 'net.ipv6.conf.default.disable_ipv6 = 1' >> /etc/sysctl.conf
echo 'net.ipv6.conf.lo.disable_ipv6 = 1' >> /etc/sysctl.conf
systemctl restart networking.service

(Obviously if this is done before the DNS systemctl restart networking.service then this only needs to be done once).

Finally, the Ubuntu template appears to use 'Flexible' network adapter instead of VMXNET3 - have tried changing this in the .ova prior to template customisation and appears to work fine, not sure if this can be built in to the script processing or not?

**Comment by pacogomez** [comment]
Hi Jon,
Thanks for opening this issue. I'm aware of error 1 and will provide an updated script soon. The error seems to be due to Org VDC configured with fast provisioning (credit goes to @tsugliani for pointing this out). In those cases the two commands will fail, so I'm adding code to consider the fact that the disks can't be resized.
I will add the ipv6 lines suggested. Thanks.
We are planing to add code in [pyvcloud](GitHub.com/vmware/pyvcloud) to change the NIC type. Once this code is ready, we can include a NIC configuration step in the template preparation. @sompa @sahithi
