### ISSUE TITLE
Change default storage policy of CSE Template without recreating them from scratch

### ISSUE THREAD

**Issue by hiteshsharma0** [vmware/container-service-extension#740]
I am trying to find a work around of quickly changing the storage policy of the templates without recreating them every time. Also we want to do so without defining the storage policy flag in the command line.

CSE vAPp templates were originally stored on “Silver” storage policy. What we observe, after moving the templates to “Tier-1” storage policy, is that every cluster we deploy without forcing target policy from command line gets deployed to the ”Silver” policy. 

We did few attempts to solve this behavior, and all of them failed – 

1.	On deployment’s target Org-vDC, we changed the default storage policy to “Tier-1” – no effect, by default CSE clusters still go to “Silver”.
2.	As you know, on CSE config.yaml there is an option to specify the default storage policy on which CSE clusters should be deployed – we set that to the desired storage policy, and it’s not working. 
3.	We then updated one of CSE’s vApp template configuration from vCloud, and specified the “Default Storage policy” parameter, that for “plain” vCloud deployments indicates.. well, the default storage policy the vApp is deployed too. 
While this works just fine for normal vApps, for CSE clusters it is ignored and clusters get deployed to “Silver”. 

In no way, we are able to modify CSE’s default storage policy for clusters deployment. As per VMware github docs, this setting should be configured on CSE config.yaml file parameter “storage_profile” (you can refer here) – but it doesn’t work. It looks like some parameter on CSE server or vApp templates side, still stores the “Silver” storage policy configuration and uses that as default deployment policy. 
Therefore, we need  to identify this setting and help us correct it.

**Comment by sahithi** [comment]
Hi Hitesh,

This is the expected behavior as CSE stands today. However, we do understand your concern.

The _storage_profile_ property in the _config.yaml_ represents the _storage_profile_ with which CSE templates need to be created. It does not represent the default storage profile for all cluster deployments.

vCD templates are immutable. This is what is causing this inconvenience for CSE templates.

It may not be a good approach to set one default storage-profile in _config.yaml_ for all tenants, as it has to be a tenant choice rather than the provider choice.

I don't see any other alternative other than recreating templates (or) attempting other strategies that providers or tenants use to storage VMotion templates or vms.

We will internally discuss a long term solution to address this issue. 

Sahithi.

**Comment by hiteshsharma0** [comment]
Hello Sahithi,

Thanks for your response. Is it somehow, we can log it as a feature request for the upcoming releases?

**Comment by sahithi** [comment]
Sure, I have filed an internal feature request on your behalf. We will consider addressing it for the next release.

Thanks.

**Comment by hiteshsharma0** [comment]
Hello Sahithi,

 

Can you please share the feature request number so that we can get it tracked through VMware TAM?

 

Thanks & Regards!

cid:image001.gif@01D3CED3.793E3E60

Hitesh Sharma
Tech Lead – L2 Solutions Team

OCB | Private Cloud Operations INDIA

CVS : 73593096

Mobile: +918376908473

Hitesh1.sharma@orange.com
4th Floor, Building No 8A, DLF Cyber City, Phase II, Sector 25, Gurgaon – 122002, Haryana, India
 <http://www.orange-business.com/> www.orange-business.com
