### ISSUE TITLE
URLs or IPs to whitelist dockerhub

### ISSUE THREAD

**Issue by sreejesh-d** [vmware/container-service-extension#816]
Hi All,

I believe in CSE by default the nodes use docker.  And the default registry for docker is dockerhub. Do we've list of URLS or IPs associated to dcokerhub to whitelist them in the firewall?

**Comment by Anirudh9794** [comment]
CSE uses apt-get to install prerequisites such as docker, kubeadm, kubelet and some other dependencies needed to install the cluster and kubeadm is used to create control plane and worker nodes. We don't maintain any list of URLs or IPs associated with these since it is possible that the URLs or IPs used can change.

**Comment by sreejesh-d** [comment]
thanks for the update.
