### ISSUE TITLE
Facing issue to upgrade the template through proxy

### ISSUE THREAD

**Issue by PradeepRanjan18** [vmware/container-service-extension#959]
Hi Team,

We are using proxy in our production CSE server and facing issue while upgrading the template. we have already checked and required flow are in placed at proxy level.

it seems that issue related to certificate and we tried to update the certificate through "openssl-c_rehash". However, package is not available on CSE server, so manually download the package and tried to install the same. again, it's failed because multiple dependency package. I tried to download the dependency package manually from photon-os repository. but could not able to find all package there.

Could you please look into it and try to help me asap.

Error:

 [ /tmp ]# rpm -i openssl-c_rehash-1.0.2q-1.ph3.x86_64.rpm
error: Failed dependencies:
        openssl = 1.0.2q-1.ph3 is needed by openssl-c_rehash-1.0.2q-1.ph3.x86_64
        perl-DBD-SQLite is needed by openssl-c_rehash-1.0.2q-1.ph3.x86_64
        perl-DBI is needed by openssl-c_rehash-1.0.2q-1.ph3.x86_64
        perl-DBIx-Simple is needed by openssl-c_rehash-1.0.2q-1.ph3.x86_64

Thank you.

**Comment by sahithi** [comment]
Hi Pradeep,

It is not clear from the description whether the issue is with the environment (or) CSE server. 

CSE server uses a proxy. Then an attempt is made to upgrade a template from one version to another? Is template upgrade failing with the above error? (or) is it being thrown on the CSE server start-up? Regardless, this looks like an OS environment issue (not related to the CSE server), and if you think it is just a dependency issue, please install all the dependencies.

If you think this is something to do with CSE server, please share your thoughts on why, and elaborate more on the environment and reproduction steps. Do upload CSE server debug logs and mention the CSE server version, template name, and revision you are upgrading from and to.

Thanks
Sahithi.

**Comment by PradeepRanjan18** [comment]
Hi Sahithi,

Thank you for your response.

The main concern with CSE's Server Proxy. i was able to install package and updated the certificated on CSE Server to access the internet through proxy. Also, verified all details and port flow on proxy server. However, not able to reach the internet on CSE server. As we have already verified flow and other setting which looks good to environment point of view. We are doing all this efforts to upgrade the template but seems we are getting stuck at CSE Server level.

Please share your valuable feedback.

**Comment by sahithi** [comment]
Hi Pradeep,

Are you talking about the proxy set at OS level? If that works, CSE server should also be able to reach the internet just fine. 

What do you mean by "CSE's server proxy"? where are you setting this proxy?

**Comment by PradeepRanjan18** [comment]
HI Sahithi,

yes, proxy at OS level. this might be issue not related to CSE but related to Photon. certificate issue at Photon level. we have already  updated the certificate but seems it's not working and not sure how to fix the same.

can you please look into it and help us to resolve the same.

**Comment by arunmk** [comment]
Hi Pradeep, from what I understand, you are downloading all packages on an external machine and scp-ing it to the machine on which cse server runs. And this operation fails due to missing dependencies. Is that correct?

If that is the case, could you try recursively downloading all packages needed using the `yum install --downloadonly` command? For example, from https://unix.stackexchange.com/a/174485/159513

```
yum install \
  --installroot=</path/to/tmp_dir> \
  --downloadonly --downloaddir <rpm_dir> <package>
```

Note: if you don't have the plugin on the machine from which you plan to download the packages, one of the following commands should work:
```
yum install yum-downloadonly
yum install yum-plugin-downloadonly
```

**Comment by PradeepRanjan18** [comment]
Hi Arun,

yes, I was facing the challenge for package. However, now it's fixed and able to install package with the help of ISO image.

However, the main concern is still there and it seems proxy certificate is not being installed/updated successfully. we try to reach the internet from CSE VM through proxy. but somehow it's getting stuck at certificate level and didnt get clue how to fix this.

**Comment by arunmk** [comment]
hi @PradeepRanjan18 , at this point I would suggest that you use the support from Photon. They should have a better and more extensive set of options in such scenarios.
